#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
sysctl -wq net.core.bpf_jit_enable=1

cat <<EOF


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

  _____         _   _     _
 |_   _|__  ___| |_| |   (_)_ __  _   ___  __
   | |/ _ \/ __| __| |   | | '_ \| | | \ \/ /
   | |  __/\__ \ |_| |___| | | | | |_| |>  <
   |_|\___||___/\__|_____|_|_| |_|\__,_/_/\_\



Welcome to $(uname -sr) running on $(uname -m) in QEMU
Press Ctrl-a x to terminate

EOF

exec /bin/sh
